- mix.exs
- priv/templates/components/progress.eex
> Fix un-csp progress mounted

- CHANGELOG.md
- mix.exs
- priv/templates/components/modal.eex
- priv/templates/components/progress.eex
> Fix modal title default value

- priv/templates/components/button.eex
- priv/templates/components/button.exs
This pull request updates the color scheme for all button variants, adds full support for dark mode, and addresses issues with gradient styles. The goal is to improve the visual consistency and accessibility of buttons across light and dark themes.
**Changes Made**
1. Updated Button Colors:
- Refined color palette for all button variants (primary, secondary, success, warning, danger, etc.) to enhance readability and visual appeal.
- Ensured colors meet accessibility contrast guidelines.
2. Dark Mode Support:
- Added full support for dark mode, ensuring buttons adjust their colors appropriately based on the current theme.
- Updated styles for hover, active, and focus states to match the dark mode theme.
3. Gradient Fixes:
- Resolved issues with gradient, outline gradient, and inverted …
> Enhancement - Modify colors of button component, add dark mode, fix issues of gradient variants

- lib/mix/tasks/mishka.ui.add.ex
- lib/mix/tasks/mishka.ui.gen.component.ex
- lib/mix/tasks/mishka.ui.gen.components.ex
> Cli 0.0.2 supports helpers import

- priv/templates/components/badge.eex
- priv/templates/components/badge.exs
- priv/templates/components/button.eex
This pull request addresses multiple style updates and color modifications across various components. The focus was to refine the visual appearance and ensure a cohesive design throughout the application.
1. **Color Updates**:
- Modified existing colors
2. **Removed Unbordered Variant**:
- Deprecated the `unbordered` variant for components as it no longer aligns with the current design standards.
3. **Style Fixes**:
- Removed line height class from content of badge.
- Adjusted typography styles.
- Added border classes for the `outline` variant.
- Button Component Styling Adjustments:
- Fix issues of colors in `color_variant` functions
> chore: update Badge component styles, and modified colors

- priv/templates/components/divider.eex
- priv/templates/components/divider.exs
- priv/templates/components/drawer.eex
- priv/templates/components/drawer.exs
**Summary**: This PR updates the `Divider` by modifying all existing color styles and adding support for dark mode.
**Changes**:
- Updated color definitions for improved consistency.
- Added dark mode variants for all colors.
>  Enhancing Divider Component with New Colors and Dark Mode Support

- CHANGELOG.md
- priv/templates/components/avatar.eex
- priv/templates/components/avatar.exs
**Summary**: This PR updates the `Avatar` by modifying all existing color styles and adding support for dark mode.
**Changes**:
- Updated color definitions for improved consistency.
- Added dark mode variants for all colors.
> chore: update Avatar colors and add dark mode support

- CHANGELOG.md
- priv/templates/components/alert.eex
- priv/templates/components/alert.exs
**Summary**
This PR updates the application by modifying alert colors and introduces a new dark mode theme.
**Changes**
- Updated alert colors to improve contrast.
- Added dark mode support across the entire component variants.
> Chore: Modify Alert component colors and add dark mode

- CHANGELOG.md
- priv/templates/components/spinner.eex
- priv/templates/components/spinner.exs
**Description**:
- Updated spinner colors.
- Added dark mode support .
> Chore: Modify colors of spinner, Add dark mode

- CHANGELOG.md
- priv/templates/components/banner.eex
- priv/templates/components/banner.exs
**Summary:**
- change colors of variants
- Add dark mode to the variants
> Chore: Modify colors, add dark mode to banner component

- CHANGELOG.md
- priv/templates/components/breadcrumb.eex
- priv/templates/components/breadcrumb.exs
**Summary:**
- Modify all the colors
- Add dark mode to all colors
> Chore: Modify colors and dark mode of breadcrumb

- CHANGELOG.md
- priv/templates/components/blockquote.eex
- priv/templates/components/blockquote.exs
**Summary:**
-  Modify colors of blockquote
- Add dark mode
- rename `unbordered` to `bordered` variant
> Chore: Change colors and add dark mode of blockquote

- CHANGELOG.md
- priv/templates/components/dropdown.eex
- priv/templates/components/dropdown.exs
**Summary:**
- Add dark mode to dropdown
- Change colors of variants
> Chore: Modify colors, variants  and add dark mode to dropdown 

- CHANGELOG.md
- priv/templates/components/overlay.eex
- priv/templates/components/overlay.exs
**Summary:**
- Ass support to dark mode
> Chore: Change colors of overlays , add dark mode

- CHANGELOG.md
- priv/templates/components/card.eex
- priv/templates/components/card.exs
**Summary:**
- add dark mode
- Rename `unbordered` to `bordered`  so the component now has a lighter background with border variant
> Chore: Change colors of card and add dark mode

- CHANGELOG.md
- priv/templates/components/card.eex
- priv/templates/components/card.exs
**Summary:**
- Add gradient variant to card component
- Add white and dark colors to `bordered` and `default` variants
> Feat: Add new variant and colors to card component

- priv/templates/components/banner.eex
- priv/templates/components/banner.exs
**Summary**:
- Add `gradient` and `bordered` variants
- add `white` and `dark` colors to `bordered` and `default` variants
> Feat: Add gradient and bordered variants to banner

- priv/templates/components/alert.eex
- priv/templates/components/alert.exs
**Summary**
- Add `gradient` and `bordered` variants
- Add Add `white` and `dark` colors to Add `default` and `bordered` variants
> Feat: Add `gradient` and `bordered` variants

- priv/templates/components/button.eex
- priv/templates/components/button.exs
Summary:
- Add `bordered` gradient to button
- Add `dark` and `white` colors to default variant
> Feat: Add `bordered` gradient to button

- priv/templates/components/dropdown.eex
- priv/templates/components/dropdown.exs
**Summary**:
- Add gradient variant
- add white and dark colors to default and bordered variants
> Feat: Add gradient to dropdown component

- priv/templates/components/overlay.eex
- priv/templates/components/overlay.exs
> Chore: Add new dark and white colors to overlay

- CHANGELOG.md
- priv/templates/components/rating.eex
- priv/templates/components/rating.exs
- Add dark mode to the component
> Chore: Modify colors, Introduce dark mode to rating component

- CHANGELOG.md
- priv/templates/components/chat.eex
- priv/templates/components/chat.exs
- change colors
- add dark mode
> Chore: Change colors, Introduce dark mode to chat component

- CHANGELOG.md
- priv/templates/components/modal.eex
- priv/templates/components/modal.exs
- add `gradient` variant
- change colors
- add dark mode
> Feat: add gradient variant, change colors, add dark mode

- CHANGELOG.md
- priv/templates/components/keyboard.eex
- priv/templates/components/keyboard.exs
> Chore: Modify colors of keyboard and add dark mode

- CHANGELOG.md
- priv/templates/components/jumbotron.eex
- priv/templates/components/jumbotron.exs
> Chore: Modify colors of jumbotron, add dark mode to component

- priv/templates/components/progress.eex
> Chore: Change colors of gradient of progress

- priv/templates/components/image.eex
> Feat: add filter props to image component

- priv/templates/components/timeline.eex
- Apply different styles to lines, such as dotted, dashed, or solid.
- Adjust the component to resize borders in horizontal mode.
Close #20 
Close #19
> Feat: Add other line styles to timeline

- priv/templates/components/button.eex
Add a `loading` slot to the button component to include loading HTML content or use Mishka Chelekom's `<.spinnr />` component for the loading state.
Close: #48
> Feat: Add loader to slot to button component

- priv/templates/components/toggle_field.eex
> Feat: Add radius to toggle component

- priv/templates/components/pagination.eex
- priv/templates/components/timeline.eex
> Feat: add space based on sizes to pagination component

- CHANGELOG.md
- mix.exs
- priv/templates/components/table.eex
- priv/templates/components/table.exs
- A new `separated` variant has been added to the table's variants.  
- The rounded functions have been updated to support the `separated` variant.
Close #39
> Feat: add separated variant to table

- CHANGELOG.md
- priv/templates/components/date_time_field.eex
- priv/templates/components/email_field.eex
- priv/templates/components/number_field.eex
- priv/templates/components/password_field.eex
- priv/templates/components/search_field.eex
- priv/templates/components/tel_field.eex
- priv/templates/components/text_field.eex
- priv/templates/components/textarea_field.eex
- priv/templates/components/url_field.eex
> Refactor: Fix issue of zooming inputs

- CHANGELOG.md
- lib/mix/tasks/mishka.ui.gen.component.ex
- priv/templates/components/file_field.eex
> Refactor: Stop spinner when an image is in done

- priv/templates/components/table_content.eex
> Chore: Modify table content component

- priv/templates/components/spinner.eex
- priv/templates/components/stepper.eex
- priv/templates/components/stepper.exs
Close: #21
Close: #22
Close: #23
> Feat: Add variant to stepper, add loading state to stepper

- priv/templates/components/list.eex
> Feat: add hoverable prop to list

- priv/templates/components/sidebar.eex
- priv/templates/components/sidebar.exs
> Feat: Add base color & variant to Sidebar

- CHANGELOG.md
- lib/mix/tasks/mishka.ui.add.ex
- lib/mix/tasks/mishka.ui.export.ex
- lib/mix/tasks/mishka.ui.gen.component.ex
> Add export task for Community cli and fix some issues of converting

- priv/components/tabs.eex
> Chore: Add panel class attribute to tab components

- priv/assets/js/floating.js
- priv/components/dropdown.eex
- priv/components/dropdown.exs
> Refactor: Fix Dropdown Bugs and Enhance Dynamic Behavior

- priv/components/button.eex
- priv/components/divider.eex
> Refactor: add conditional styling to divider and buttons

- CHANGELOG.md
- priv/assets/js/galleryFilter.js
- priv/components/gallery.eex
- priv/components/gallery.exs
 Close #10 
https://github.com/user-attachments/assets/c61693fa-e3be-45e3-b1be-c74b75834eec
> Feat: add filterable gallery component

- CHANGELOG.md
- priv/components/progress.eex
- priv/components/progress.exs
> Feat: add ring and semi circle progress components

- CHANGELOG.md
- priv/components/rating.eex
> Feat: Add fraction support to rating component

- CHANGELOG.md
- mix.exs
- priv/components/progress.eex
- priv/components/progress.exs
> Feat: add tooltip to progress section

- CHANGELOG.md
- mix.exs
- priv/assets/js/carousel.js
- priv/assets/js/combobox.js
- priv/components/carousel.eex
- priv/components/carousel.exs
- priv/components/navbar.eex
> Refactor: add custom hook and loading state, fix bugs in Carousel component

- CHANGELOG.md
- priv/assets/js/clipboard.js
- priv/components/clipboard.eex
- priv/components/clipboard.exs
> Feat: Add Clipboard component and hook integration

- CHANGELOG.md
- mix.exs
- priv/assets/js/sidebar.js
- priv/components/sidebar.eex
- priv/components/sidebar.exs
- priv/components/tooltip.eex
> Feat: Add ability to to Minimize and Maximize Sidebar

- priv/components/accordion.eex
- priv/components/icon.eex
> feat: enhance accessibility via aria-expanded and roles for accordion

- priv/components/alert.eex
> feat(alert): improve accessibility and add class props to elements

- priv/components/badge.eex
> feat(badge): improve accessibility and add class props to elements

- priv/components/banner.eex
> feat(banner): improve accessibility and add class props to elements

- priv/components/blockquote.eex
> feat(blockquote): improve accessibility and add class props to elements

- priv/components/blockquote.eex
- priv/components/breadcrumb.eex
> feat(breadcrumb): improve accessibility and add class props to elements

- priv/components/card.eex
> feat(card): improve accessibility and add class props to elements

- priv/components/chat.eex
> feat(chat): improve accessibility and add class props to elements

- priv/components/checkbox_card.eex
> feat(checkbox_card): improve accessibility and add class props to elements

- priv/components/navbar.eex
based on https://github.com/mishka-group/mishka_chelekom/issues/41 https://github.com/mishka-group/mishka_chelekom/issues/131 https://github.com/mishka-group/mishka_chelekom/issues/88 
Close: https://github.com/mishka-group/mishka_chelekom/issues/347
> feat(navbar): improve accessibility and add class props to elements

- priv/assets/js/clipboard.js
- priv/components/clipboard.eex
> feat(clipboard): improve accessibility and add class props to elements

- priv/components/combobox.eex
> feat(combobox): improve accessibility and add class props to elements

- priv/assets/js/floating.js
- priv/components/dropdown.eex
> feat(dropdown): improve accessibility and add class props to elements

- priv/components/button.eex
> feat(button): improve accessibility and add class props to elements

- priv/components/footer.eex
> feat(footer): improve accessibility and add class props to elements

- priv/components/gallery.eex
> feat(gallery): improve accessibility and add class props to elements

- priv/components/mega_menu.eex
> feat(mega_menu): improve accessibility and add class props to elements

- priv/components/overlay.eex
> feat(overlay): improve accessibility and add class props to elements

- priv/components/radio_card.eex
> feat(radio_card): improve accessibility and add class props to elements

- priv/components/rating.eex
> feat(rating): improve accessibility and add class props to elements

- priv/components/scroll_area.eex
> feat(scroll_area): improve accessibility and add class props to elements

- priv/components/sidebar.eex
> feat(sidebar): improve accessibility and add class props to elements

- priv/components/skeleton.eex
> feat(skeleton): improve accessibility and add class props to elements

- priv/components/speed_dial.eex
> feat(speed_dial): improve accessibility and add class props to elements

- priv/components/stepper.eex
> feat(stepper): improve accessibility and add class props to elements

- priv/components/spinner.eex
> feat(spinner): improve accessibility and add class props to elements

- priv/components/table_content.eex
> feat(table_content): improve accessibility and add class props to elements

- priv/components/table.eex
> feat(table): improve accessibility and add class props to elements

- priv/components/tabs.eex
> feat(tabs): improve accessibility and add class props to elements

- priv/components/timeline.eex
> feat(timeline): improve accessibility and add class props to elements

- priv/components/toggle_field.eex
> feat(toggle_field): improve accessibility and add class props to elements

- priv/components/tooltip.eex
> feat(tooltip): improve accessibility and add class props to elements

- priv/components/toast.eex
> feat(toast): improve accessibility and add class props to elements

- priv/components/avatar.eex
> Refactor: Fix display of avatar component

- CHANGELOG.md
- lib/mix/tasks/mishka.ui.gen.components.ex
- mix.exs
- priv/components/alert.exs
Based on https://github.com/phoenixframework/phoenix/issues/6292
> Flash group restriction for Phoenix version 1.8

- lib/mix/tasks/mishka.ui.gen.component.ex
- priv/components/date_time_field.eex
- priv/components/email_field.eex
- priv/components/number_field.eex
- priv/components/password_field.eex
- priv/components/search_field.eex
- priv/components/tel_field.eex
- priv/components/text_field.eex
- priv/components/textarea_field.eex
- priv/components/url_field.eex
> fix: Typo flaoting and inpendut
